version: '3.3'
services:

# MS - USER_SERVICE
    db_user_service: 
        image: mysql:5.7.26
        environment:
            MYSQL_DATABASE: db_user_service
            MYSQL_USER: db_user_service
            MYSQL_PASSWORD: db_user_service
            MYSQL_ROOT_PASSWORD: 'random-root-password'
        volumes:
            - ~/databases/db_user_service/data:/var/lib/mysql
        networks:
            - network_backend

    user_service:
        build: ./microservices/user-service
        volumes:
            - ./microservices/user-service:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            DB_USERNAME: db_user_service
            DB_PASSWORD: db_user_service
            DB_NAME: db_user_service
            DB_HOST: db_user_service

            FILE_STORE_SECRET_KEY: 'secret'
            PASSPORT_SECRET_KEY: 'secret'
            JWT_SECRET_KEY: 'secret'
    
        ports:
            - 3001:3000
        networks:
            - network_backend
        depends_on:
            - db_user_service
        restart: always
        command: ["./wait-for-it.sh", "db_user_service:3306", "--", "nodemon"]
        

# MS - OCR-SERVICE
    db_ocr_service: 
        image: mysql:5.7.26
        environment:
            MYSQL_DATABASE: db_ocr_service
            MYSQL_USER: db_ocr_service
            MYSQL_PASSWORD: db_ocr_service
            MYSQL_ROOT_PASSWORD: 'random-root-password'
        volumes:
            - ~/databases/db_ocr_service/data:/var/lib/mysql
        networks:
            - network_backend

    ocr_service:
        build: ./microservices/ocr-service
        volumes:
            - ./microservices/ocr-service:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            DB_USERNAME: db_ocr_service
            DB_PASSWORD: db_ocr_service
            DB_NAME: db_ocr_service
            DB_HOST: db_ocr_service

        ports:
            - 3002:3000
        networks:
            - network_backend
        depends_on:
            - db_ocr_service
        restart: always

        # TODO : Change on deploy
        # command: ["./wait-for-it.sh", "db_ocr_service:3306",  "--", "npm start"]

# MS - MAIN_SERVICE
    db_main_service: 
        image: mysql:5.7.26
        environment:
            MYSQL_DATABASE: db_main_service
            MYSQL_USER: db_main_service
            MYSQL_PASSWORD: db_main_service
            MYSQL_ROOT_PASSWORD: 'random-root-password'
        volumes:
            - ~/databases/db_main_service/data:/var/lib/mysql
        networks:
            - network_backend

    main_service:
        build: ./microservices/main-service
        volumes:
            - ./microservices/main-service:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            DB_USERNAME: db_main_service
            DB_PASSWORD: db_main_service
            DB_NAME: db_main_service
            DB_HOST: db_main_service

            # MS_GENERIC_SERVICE: 'http://generic_service:3000'
        ports:
            - 3003:3000
        networks:
            - network_backend
        depends_on:
            - db_main_service
        restart: always
        command: ["./wait-for-it.sh", "db_main_service:3306", "--", "nodemon"]

networks:
    network_backend:
        driver: "bridge"
    network_frontend:
        driver: "bridge"
