version: '3.3'
services:

# MS - USER_SERVICE
    db_user_service: 
        image: mysql:5.7.34
        environment:
            MYSQL_DATABASE: user_service
            MYSQL_USER: user_service
            MYSQL_PASSWORD: user_service
            MYSQL_ROOT_PASSWORD: 'random-root-password'
        volumes:
            - ~/databases/db_user_service/data:/var/lib/mysql
        networks:
            - network_backend

    user_service:
        build: ./microservices/user-service
        volumes:
            - ./microservices/user-service:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            DB_USERNAME: user_service
            DB_PASSWORD: user_service
            DB_NAME: user_service
            DB_HOST: db_user_service

            FILE_STORE_SECRET_KEY: 'secret'
            PASSPORT_SECRET_KEY: 'secret'
            JWT_SECRET_KEY: 'secret'
    
            MS_GENERIC_SERVICE: 'http://generic_service:3000'
        ports:
            - 3001:3000
        networks:
            - network_backend
        depends_on:
            - db_user_service
        restart: always
        command: ["./wait-for-it.sh", "db_user_service:3306", "--", "nodemon"]

# MS - GENERIC-SERVICE
    db_generic_service: 
        image: mysql:5.7.34
        environment:
            MYSQL_DATABASE: db_generic_service
            MYSQL_USER: db_generic_service
            MYSQL_PASSWORD: db_generic_service
            MYSQL_ROOT_PASSWORD: 'random-root-password'
        volumes:
            - ~/databases/db_generic_service/data:/var/lib/mysql
        networks:
            - network_backend

    generic_service:
        build: ./microservices/generic-service
        volumes:
            - ./microservices/generic-service:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            DB_USERNAME: db_generic_service
            DB_PASSWORD: db_generic_service
            DB_NAME: db_generic_service
            DB_HOST: db_generic_service

            MS_USERS: 'http://user_service:3000'

        ports:
            - 3002:3000
        networks:
            - network_backend
        depends_on:
            - db_generic_service
        restart: always
        command: ["./wait-for-it.sh", "db_generic_service:3306",  "--", "nodemon"]

networks:
    network_backend:
        driver: "bridge"
    network_frontend:
        driver: "bridge"
